import { z } from "zod";

export default z.enum([
  "TECHNICAL_SUPPORT_SPECIALIST",
  "HELP_DESK_SUPPORT_MANAGER",
  "SYSTEMS_SECURITY_MANAGER",
  "ERP_INTEGRATION_MANAGER",
  "CLOUD_SERVICE_DELIVERY_MANAGER",
]);
